# Site wide configuration

title: Fastahâ„¢
description: Fastah app - the joyful mobile web for your iPhone
logo: Fastah_FullIcon_v2.png# 120x120 px default image used for Twitter summary card
teaser: Fastah_FullIcon_v2.png # 400x250 px default teaser image used in image archive grid
locale: en_US
url: http://fastah.blackbuck.mobi

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
    web: http://blackbuck.mobi
    name: Siddharth Mathur
    email: smathur@blackbuck.mobi
    twitter: s8mathur
    google:
        plus: 101767478075357933060
        ad-client: 
        ad-slot: 
        verify: 3K5EOOn8dznOk8W7ok4GkPatPeLD4D9I445mB_gJsf0
    bio: Blackbuck Computing - Purveyors of fine mobile-friendly software since 2014.
    avatar: bio-photo.jpg # 160x160 px image for author byline

disqus-shortname: blackbuck


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
